version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0

parameters:
  config_dir:
    type: integer
    default: 0
  run_hello:
    type: boolean
    default: false
  run_yaml:
    type: boolean
    default: false
  run_databases:
    type: boolean
    default: false
  run_parallelism:
    type: boolean
    default: false
  run_orbs:
    type: boolean
    default: false
    
workflows:
  get-config:
    jobs:
      - get-config

jobs:
  get-config:
    executor: continuation/default
    steps:
      - run: |
          echo run_hello: << pipeline.parameters.run_hello >>
          echo run_yaml: << pipeline.parameters.run_yaml >>
          echo config_dir: << pipeline.parameters.config_dir >>