version: 2.1

orbs:
  continuation: circleci/continuation@0.2.0

parameters:
  config-dir:
    type: string
    default: '01 Hello World'

workflows:
  get-config:
    jobs:
      - continuation/continue:
          configuration_path: << pipeline.parameters.config-dir >>/.circleci/config.yml
